services:
  - type: web
    name: starz-shots-gallery
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SPACEBYTE_BASE_URL
        value: https://spacebyte.in/api/v1
      - key: SPACEBYTE_TOKEN
        sync: false
      - key: ADMIN_TOKEN
        sync: false
